/**
 * Generates docs/openapi.json, docs/mcp-tools.json and docs/mcp-tools.md
 * from the contract schemas and tool definitions. Run: npm run docs:generate
 * A test fails if the committed files are stale.
 */

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import * as C from "../src/contracts/schemas.js";
import { ERROR_CODES, ERROR_SPECS } from "../src/domain/errors.js";
import { TOOLS } from "../src/mcp/tools.js";
import { ALL_SCOPES, SCOPE_DESCRIPTIONS } from "../src/security/scopes.js";

const DOCS = join(dirname(fileURLToPath(import.meta.url)), "..", "docs");

const schema = (s: z.ZodType, io: "input" | "output") => {
  const j = z.toJSONSchema(s, { io, unrepresentable: "any" }) as Record<string, unknown>;
  delete j.$schema;
  return j;
};

// ------------------------------------------------------------ MCP tools

export function mcpToolsJson() {
  return {
    server: "gimme-voice-commerce",
    contract_version: "1.0",
    transports: ["streamable-http (/mcp, OAuth 2.0 bearer)", "stdio (development)"],
    tools: TOOLS.map((t) => ({
      name: t.name,
      title: t.title,
      description: t.description,
      contract_version: t.contract_version,
      classification: t.classification,
      requires_authentication: t.requires_authentication,
      required_scopes: t.required_scopes,
      requires_confirmation: t.requires_confirmation,
      has_side_effect: t.has_side_effect,
      side_effects: t.side_effects,
      idempotent: t.idempotent,
      idempotency: t.idempotency,
      error_codes: t.error_codes,
      inputSchema: schema(t.inputSchema, "input"),
      outputSchema: schema(t.outputSchema, "output"),
    })),
    error_schema: schema(C.ErrorBody, "output"),
  };
}

export function mcpToolsMarkdown(): string {
  const out: string[] = [
    "# GIMME MCP tool specification",
    "",
    "_Generated by `npm run docs:generate` from `src/mcp/tools.ts` and `src/contracts/schemas.ts`. Do not edit by hand._",
    "",
    "Machine-readable version, with full JSON Schemas: [`mcp-tools.json`](mcp-tools.json).",
    "",
    "| Tool | Class | Scopes | Side effect | Idempotent | Needs customer confirmation |",
    "| --- | --- | --- | --- | --- | --- |",
    ...TOOLS.map(
      (t) =>
        `| [\`${t.name}\`](#${t.name}) | ${t.classification} | ${t.required_scopes.map((s) => `\`${s}\``).join(" ")} | ${t.has_side_effect ? "yes" : "no"} | ${t.idempotent ? "yes" : "no"} | ${t.requires_confirmation ? "**yes**" : "no"} |`,
    ),
    "",
  ];
  for (const t of TOOLS) {
    const input = schema(t.inputSchema, "input") as { properties?: Record<string, { description?: string; type?: string }>; required?: string[] };
    out.push(`## ${t.name}`, "", t.description, "");
    out.push(`- **Classification:** ${t.classification}`);
    out.push(`- **Scopes:** ${t.required_scopes.map((s) => `\`${s}\``).join(", ")}`);
    out.push(`- **Side effects:** ${t.side_effects}`);
    out.push(`- **Idempotency:** ${t.idempotency}`);
    out.push(`- **Errors:** ${t.error_codes.map((e) => `\`${e}\``).join(", ")}`, "");
    out.push("| Argument | Required | Description |", "| --- | --- | --- |");
    for (const [k, v] of Object.entries(input.properties ?? {})) {
      out.push(`| \`${k}\` | ${input.required?.includes(k) ? "yes" : "no"} | ${(v.description ?? v.type ?? "").replace(/\|/g, "\\|")} |`);
    }
    out.push("");
  }
  out.push("## Error codes", "", "| Code | HTTP | Recoverable | Suggested action | Default message |", "| --- | --- | --- | --- | --- |");
  for (const c of ERROR_CODES) {
    const s = ERROR_SPECS[c];
    out.push(`| \`${c}\` | ${s.http} | ${s.recoverable ? "yes" : "no"} | \`${s.action}\` | ${s.message} |`);
  }
  out.push("");
  return out.join("\n");
}

// -------------------------------------------------------------- OpenAPI

type Op = { method: "get" | "post"; path: string; summary: string; scopes: string[]; body?: z.ZodType; response: z.ZodType | null; status?: number; params?: string[]; query?: z.ZodObject; idempotencyHeader?: boolean; security?: false; description?: string };

const OPS: Op[] = [
  { method: "post", path: "/v1/voice/sessions", summary: "Open a voice session (handshake, identify_customer)", scopes: ["gimme.customer.read"], body: C.IdentifyCustomerInput, response: C.IdentifyCustomerOutput, status: 201 },
  { method: "get", path: "/v1/voice/sessions/{id}", summary: "Read a voice session", scopes: [], params: ["id"], response: C.SessionView },
  { method: "post", path: "/v1/voice/resolve", summary: "Resolve spoken items, usual order or last order to SKUs", scopes: ["gimme.products.read", "gimme.customer.read"], body: C.ResolveItemsInput, response: C.ResolveItemsOutput },
  { method: "post", path: "/v1/voice/products/search", summary: "Search products", scopes: ["gimme.products.read"], body: C.SearchProductsInput, response: C.SearchProductsOutput },
  { method: "get", path: "/v1/voice/preferences", summary: "Customer preferences", scopes: ["gimme.customer.read"], query: C.GetPreferencesInput, response: C.GetPreferencesOutput },
  { method: "post", path: "/v1/voice/inventory/check", summary: "Check live stock", scopes: ["gimme.inventory.read"], body: C.CheckInventoryInput, response: C.CheckInventoryOutput },
  { method: "post", path: "/v1/voice/delivery/validate", summary: "Check delivery eligibility", scopes: ["gimme.inventory.read"], body: C.ValidateDeliveryInput, response: C.ValidateDeliveryOutput },
  { method: "post", path: "/v1/voice/customer/validate", summary: "Check purchase eligibility", scopes: ["gimme.customer.read"], body: C.ValidateCustomerInput, response: C.ValidateCustomerOutput },
  { method: "post", path: "/v1/voice/cart/calculate", summary: "Price a basket (informational quote)", scopes: ["gimme.cart.create"], body: C.CalculateCartInput, response: C.CalculateCartOutput },
  { method: "post", path: "/v1/voice/order-intents", summary: "Create an order intent awaiting confirmation", scopes: ["gimme.cart.create"], body: C.CreateOrderIntentInput, response: C.CreateOrderIntentOutput, status: 201, idempotencyHeader: true },
  { method: "get", path: "/v1/voice/order-intents/{id}", summary: "Read an order intent", scopes: ["gimme.cart.create"], params: ["id"], response: C.GetOrderIntentOutput },
  {
    method: "post",
    path: "/v1/voice/order-intents/{id}/confirmation-request",
    summary: "Start customer confirmation; returns a single-use GIMME-hosted confirmation link",
    scopes: ["gimme.cart.create"],
    params: ["id"],
    response: z.object({ order_intent: C.OrderIntentView, confirmation_url: z.string() }),
  },
  {
    method: "post",
    path: "/v1/voice/order-intents/{id}/confirm",
    summary: "Record the customer's confirmation (first-party clients only)",
    description: "Called by GIMME's own apps after the platform's native purchase confirmation. confirmed_total must equal the intent total exactly; device_authenticated must be true on platforms that require it.",
    scopes: ["gimme.order.confirm"],
    params: ["id"],
    body: C.ConfirmOrderIntentInput,
    response: C.RequestAuthorizationOutput,
  },
  { method: "post", path: "/v1/voice/order-intents/{id}/authorize-payment", summary: "Authorize payment for a confirmed intent", scopes: ["gimme.payment.authorize"], params: ["id"], body: C.AuthorizePaymentInput.omit({ order_intent_id: true }), response: C.AuthorizePaymentOutput },
  { method: "post", path: "/v1/voice/orders", summary: "Place the order", scopes: ["gimme.order.create"], body: C.PlaceOrderInput.partial({ idempotency_key: true }), response: C.PlaceOrderOutput, status: 201, idempotencyHeader: true },
  { method: "post", path: "/v1/voice/orders/reorder", summary: "Rebuild a previous order as a new intent", scopes: ["gimme.order.read", "gimme.cart.create"], body: C.ReorderInput, response: C.ReorderOutput, status: 201, idempotencyHeader: true },
  { method: "get", path: "/v1/voice/orders/latest", summary: "Status of the most recent order", scopes: ["gimme.order.read"], query: C.GetOrderStatusInput.omit({ order_id: true }), response: C.GetOrderStatusOutput },
  { method: "get", path: "/v1/voice/orders/{id}", summary: "Order status", scopes: ["gimme.order.read"], params: ["id"], response: C.GetOrderStatusOutput },
  { method: "get", path: "/v1/voice/orders/{id}/receipt", summary: "Order receipt", scopes: ["gimme.order.read"], params: ["id"], response: C.GetReceiptOutput },
  { method: "post", path: "/v1/voice/orders/{id}/cancel", summary: "Request cancellation", scopes: ["gimme.order.cancel"], params: ["id"], body: C.CancelOrderInput.omit({ order_id: true }), response: C.CancelOrderOutput },
  { method: "post", path: "/v1/voice/dialog/turn", summary: "Platform-neutral dialog turn (see docs/voice-api.md)", scopes: [], body: z.object({}).loose(), response: z.object({}).loose() },
  { method: "post", path: "/v1/voice/adapters/apple/intents", summary: "Apple App Intents adapter (see docs/apple-integration.md)", scopes: [], body: z.object({}).loose(), response: z.object({}).loose() },
  { method: "post", path: "/v1/voice/adapters/google/fulfillment", summary: "Google adapter (see docs/google-integration.md)", scopes: [], body: z.object({}).loose(), response: z.object({}).loose() },
];

export function openApi() {
  const paths: Record<string, Record<string, unknown>> = {};
  for (const op of OPS) {
    const parameters: unknown[] = [
      ...(op.params ?? []).map((p) => ({ name: p, in: "path", required: true, schema: { type: "string" } })),
      { name: "GIMME-API-Version", in: "header", required: false, schema: { type: "string", enum: ["1.0"] } },
      { name: "X-Request-Id", in: "header", required: false, schema: { type: "string" } },
      { name: "X-Correlation-Id", in: "header", required: false, schema: { type: "string" } },
      ...(op.idempotencyHeader ? [{ name: "Idempotency-Key", in: "header", required: false, schema: { type: "string", minLength: 8, maxLength: 200 } }] : []),
    ];
    if (op.query) {
      const q = schema(op.query, "input") as { properties: Record<string, unknown>; required?: string[] };
      for (const [k, v] of Object.entries(q.properties)) parameters.push({ name: k, in: "query", required: q.required?.includes(k) ?? false, schema: v });
    }
    const status = String(op.status ?? 200);
    paths[op.path] ??= {};
    paths[op.path]![op.method] = {
      summary: op.summary,
      ...(op.description ? { description: op.description } : {}),
      operationId: `${op.method}${op.path.replace(/[{}]/g, "").replace(/[/-](\w)/g, (_m, c: string) => c.toUpperCase())}`,
      security: [{ oauth2: op.scopes }],
      parameters,
      ...(op.body ? { requestBody: { required: true, content: { "application/json": { schema: schema(op.body, "input") } } } } : {}),
      responses: {
        [status]: { description: "OK", content: { "application/json": { schema: op.response ? schema(op.response, "output") : {} } } },
        default: { description: "Error", content: { "application/json": { schema: { $ref: "#/components/schemas/Error" } } } },
      },
    };
  }
  return {
    openapi: "3.1.0",
    info: {
      title: "GIMME Voice API",
      version: "1.0.0",
      description:
        "Platform-neutral voice commerce API. Apple, Google and agent adapters call this; it maps onto the same service as the GIMME MCP tools. Amounts are decimal NZD. Every error body has error_code, message, recoverable and suggested_action.",
    },
    servers: [{ url: "https://voice.gimme.example", description: "Production (placeholder)" }, { url: "http://localhost:8787", description: "Sandbox" }],
    components: {
      securitySchemes: {
        oauth2: {
          type: "oauth2",
          description: "Tokens are issued by GIMME's authorization server (account linking). This API is a resource server only.",
          flows: {
            authorizationCode: {
              authorizationUrl: "https://auth.gimme.example/authorize",
              tokenUrl: "https://auth.gimme.example/token",
              scopes: Object.fromEntries(ALL_SCOPES.map((s) => [s, SCOPE_DESCRIPTIONS[s]])),
            },
          },
        },
      },
      schemas: { Error: schema(C.ErrorBody, "output") },
    },
    paths,
  };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(join(DOCS, "openapi.json"), `${JSON.stringify(openApi(), null, 2)}\n`);
  writeFileSync(join(DOCS, "mcp-tools.json"), `${JSON.stringify(mcpToolsJson(), null, 2)}\n`);
  writeFileSync(join(DOCS, "mcp-tools.md"), mcpToolsMarkdown());
  process.stdout.write("Wrote docs/openapi.json, docs/mcp-tools.json, docs/mcp-tools.md\n");
}
